// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwCu7CezbMxuP-Qb_H6Snfj3KvfW0DJ8o',
    appId: '1:920019057231:web:8fe75850b24ae6889c883a',
    messagingSenderId: '920019057231',
    projectId: 'skamp-f2367',
    authDomain: 'skamp-f2367.firebaseapp.com',
    storageBucket: 'skamp-f2367.firebasestorage.app',
    measurementId: 'G-K8WPR9LMXE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs9XFpU7B022cGvAbfdXOO4SGkwZ_FJsk',
    appId: '1:920019057231:android:6b25beb7425683ff9c883a',
    messagingSenderId: '920019057231',
    projectId: 'skamp-f2367',
    storageBucket: 'skamp-f2367.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgoiiE81XbDSjbWgO970fpJHkKaeacSnY',
    appId: '1:920019057231:ios:c206575d2606ae0b9c883a',
    messagingSenderId: '920019057231',
    projectId: 'skamp-f2367',
    storageBucket: 'skamp-f2367.firebasestorage.app',
    iosClientId: '920019057231-1da54pk9i4669sh67hjspc6l3323btio.apps.googleusercontent.com',
    iosBundleId: 'com.skamp.skamp',
  );
}
